### Тема "Вычисления с помощью Numpy"

#### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, 
то есть состоящий из 5 строк и 2 столбцов. 

Первый столбец должен содержать числа 1, 2, 3, 3, 1, 
а второй - числа 6, 8, 11, 10, 7. 

Будем считать, что каждый столбец - это признак, 
а строка - наблюдение. 

Затем найдите среднее значение по каждому признаку, 
используя метод mean массива Numpy. 

Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

создаем массив 5х2

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
a.shape

(5, 2)

найдем среднее по каждому признаку, результат поместим в mean_a:

In [4]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

в mean_a должно быть 2 элемента:

In [5]:
mean_a.size

2

#### Задание 2
Вычислите массив a_centered, 
отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. 

Вычисление должно производиться в одно действие. 

Получившийся массив должен иметь размер 5x2.


In [6]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
a_centered.shape

(5, 2)